# Generated by Django 4.2.1 on 2023-06-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sceanarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectifs',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='Sceanarios.scenario'),
        ),
        migrations.CreateModel(
            name='ScenarioActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('activityapprenant', models.TextField()),
                ('activityenseignant', models.TextField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Sceanarios.scenario')),
            ],
        ),
    ]
