# Generated by Django 4.2.1 on 2023-05-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
